### ISSUE TITLE
Blog item administration page is available only at the right sidebar, and blog content can not be entered.

### ISSUE THREAD

**Issue by kykckyde** [ChristopherDosin/Shopware-6-Blog-Plugin#208] opened 2023-12-12 12:26 UTC
Hi, 
I'm using SW6 v6.5.5.1. 
I installed the plugin, then npm i, and then build-administration, and now it works but I have two problems at this point.

1. the 'Blog Detail' administration page for blog editing is shown at the right of the page as sidebar. Is this the expected behaviour?
2. The content input is not available. How/where can i enter/save it?
(Please see the Screenshot: https://i.imgur.com/x3aO9X4.png)

I installed the version 2.0.7 and applied the patch #207 with the hope that it would work. But still the same. That patch was actually for the frontend, but i tried it anyway.

In order to solve the problem, i have deleted the browser and sw cache, but no way.. 

Am i missing something?

Best regards,

**Comment by ChristopherDosin** [comment] 2023-12-12 12:45
Hey @kykckyde ,

1) This is the expected behavior, since we're making use of the Shopware CMS Designer. So within the sidebar you have some settings like the blog title, Thunbmail etc.

2) Since it's the CMS Designer, you build your article with CMS elements. So just drag&drop your CMS blocks inside the CMS designer the same way you're managing a normal CMS page.

Does this solve your problem?

**Comment by ChristopherDosin** [comment] 2023-12-12 13:28
>  If i'm not wrong, when i have 10000 Blog articles, than I have 10000 layouts, which i think, is a little bit too much for the logic of cms page layouts. (

We've tested it already with a thousand articles and we couldn't see here any performance issues.
We might test it with 10.000 articles again, wouldn't be a daily case I guess, but let's see.

> That was actually what i was looking for for the sw5 blog replacement into my new sw6. Just fields for title, content etc.
Is this version still available for use? And if yes, which version please?

We had this in version 1. However: A big trade off is the flexilibty. You just have a fixed content layout.
That's why we've added the CMS designer in version to be fully flexible with your blog layouts.

We wanted to build something which gives the user the full flexiblity they already know and love from the CMS designer.

**Comment by kykckyde** [comment] 2023-12-12 14:14
Now it is clear to me, how it works and the reason behind it. If i have further questions, i'll open a new Ticket.
Thanks a lot... :)

Best regards,

**Comment by ChristopherDosin** [comment] 2023-12-12 14:24
You're more than welcome, happy blogging 👍 
I will close this issue then, feel free to open a new one in case of any questions.

**Closed by ChristopherDosin** 2023-12-12 14:24 UTC
