### ISSUE TITLE
Different dates on blog list and blog detail page

### ISSUE THREAD

**Issue by de1e7ed** [ChristopherDosin/Shopware-6-Blog-Plugin#88] opened 2022-03-14 08:50 UTC
I've noticed that the blog dates used in the listing and detail page are different from each other.
The date on the blog listing page shows the 'Published at' date.
The date on the blog detail page shows a different date.

Ps. Thank you for your awesome plugin, looking forward to v2!

![Blog detail page](https://user-images.githubusercontent.com/101553396/158136616-5ea0c28c-7f54-4511-9f5d-c730176a2f3a.jpg)
![Blog listing page](https://user-images.githubusercontent.com/101553396/158136621-1989fc12-88bc-48d6-b6e1-df82e51b3aeb.jpg)
.

**Comment by viennt** [comment] 2022-05-24 07:18
Duplicate of #19

**Comment by viennt** [comment] 2022-05-24 07:21
Hi @de1e7ed, this issue is already fixed on plugin version 1.5.6. So you would have to update the plugin.

**Closed** 2022-07-01 06:34 UTC
Labels: bug
