### ISSUE TITLE
Reopening "Custom fields" issue/request

### ISSUE THREAD

**Issue by Alphaegen** [ChristopherDosin/Shopware-6-Blog-Plugin#127] opened 2022-10-17 07:21 UTC
**Original:**
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/issues/119

I think this issue/request was overlooked, but I was wondering whether anyone kan give an update on it?

**Comment by ChristopherDosin** [comment] 2022-10-30 09:17
Duplicate of https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/issues/119

**Closed by ChristopherDosin** 2022-10-30 09:17 UTC
